name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch all history so that last modified date-times are accurate

      - name: 🐍 Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[doc]

      # - name: 👷‍ Install Dot and pandoc
      #   run: |
      #     conda install -c conda-forge pandoc
      #     conda install -c conda-forge ipython
      #     pip install sphinxcontrib-websupport
      #     sudo apt update
      #     sudo apt install -y graphviz

      # outline for a myst_nb project with sphinx
      # build with: sphinx-build -nW --keep-going -b html . ./_build/html
      - name: 🔧 Build HTML
        run: |
          invoke doc --opts "-j 4"

      - name: 🚀 Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output/html/
